from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QButtonGroup, QFrame, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStackedWidget, QTabWidget, QTextEdit,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QSize(600, 400))
        MainWindow.setMaximumSize(QSize(1280, 960))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(234, 234, 234, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(244, 244, 244, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(117, 117, 117, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(156, 156, 156, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush6 = QBrush(QColor(255, 255, 220, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush7 = QBrush(QColor(0, 0, 0, 127))
        brush7.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush8 = QBrush(QColor(117, 117, 117, 127))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        MainWindow.setPalette(palette)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(1, 420, 109, 24))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(80, 0, 71, 461))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(120, 0, 511, 451))
        self.TextStackedWidget = QWidget()
        self.TextStackedWidget.setObjectName(u"TextStackedWidget")
        self.TextTabWidget = QTabWidget(self.TextStackedWidget)
        self.TextTabWidget.setObjectName(u"TextTabWidget")
        self.TextTabWidget.setGeometry(QRect(0, 0, 511, 441))
        self.TextTabWidget.setDocumentMode(False)
        self.EncryptTextTab = QWidget()
        self.EncryptTextTab.setObjectName(u"EncryptTextTab")
        self.InputEncryptionTextBox = QTextEdit(self.EncryptTextTab)
        self.InputEncryptionTextBox.setObjectName(u"InputEncryptionTextBox")
        self.InputEncryptionTextBox.setGeometry(QRect(30, 50, 451, 71))
        self.InputEncryptionPasswordLine = QLineEdit(self.EncryptTextTab)
        self.InputEncryptionPasswordLine.setObjectName(u"InputEncryptionPasswordLine")
        self.InputEncryptionPasswordLine.setGeometry(QRect(30, 150, 191, 22))
        self.EncryptTextButton = QPushButton(self.EncryptTextTab)
        self.EncryptTextButton.setObjectName(u"EncryptTextButton")
        self.EncryptTextButton.setGeometry(QRect(400, 380, 75, 24))
        self.OutputEncryptionTextBox = QTextEdit(self.EncryptTextTab)
        self.OutputEncryptionTextBox.setObjectName(u"OutputEncryptionTextBox")
        self.OutputEncryptionTextBox.setGeometry(QRect(30, 270, 451, 71))
        self.label_4 = QLabel(self.EncryptTextTab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 20, 61, 16))
        self.label_2 = QLabel(self.EncryptTextTab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 130, 61, 16))
        self.label_3 = QLabel(self.EncryptTextTab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 240, 121, 16))
        self.TextTabWidget.addTab(self.EncryptTextTab, "")
        self.DecryptTextTab = QWidget()
        self.DecryptTextTab.setObjectName(u"DecryptTextTab")
        self.OutputDecryptionTextBox = QTextEdit(self.DecryptTextTab)
        self.OutputDecryptionTextBox.setObjectName(u"OutputDecryptionTextBox")
        self.OutputDecryptionTextBox.setGeometry(QRect(30, 270, 451, 71))
        self.DecryptTextButton = QPushButton(self.DecryptTextTab)
        self.DecryptTextButton.setObjectName(u"DecryptTextButton")
        self.DecryptTextButton.setGeometry(QRect(400, 380, 75, 24))
        self.InputDecryptionTextBox = QTextEdit(self.DecryptTextTab)
        self.InputDecryptionTextBox.setObjectName(u"InputDecryptionTextBox")
        self.InputDecryptionTextBox.setGeometry(QRect(30, 50, 451, 71))
        self.InputDecryptionPasswordLine = QLineEdit(self.DecryptTextTab)
        self.InputDecryptionPasswordLine.setObjectName(u"InputDecryptionPasswordLine")
        self.InputDecryptionPasswordLine.setGeometry(QRect(30, 150, 191, 22))
        self.label_7 = QLabel(self.DecryptTextTab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 20, 111, 16))
        self.label_5 = QLabel(self.DecryptTextTab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 130, 111, 16))
        self.label_6 = QLabel(self.DecryptTextTab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 240, 131, 16))
        self.TextTabWidget.addTab(self.DecryptTextTab, "")
        self.stackedWidget.addWidget(self.TextStackedWidget)
        self.FileStackedWidget = QWidget()
        self.FileStackedWidget.setObjectName(u"FileStackedWidget")
        self.FileTabWidget = QTabWidget(self.FileStackedWidget)
        self.FileTabWidget.setObjectName(u"FileTabWidget")
        self.FileTabWidget.setGeometry(QRect(0, 0, 511, 441))
        self.EncryptFileTab = QWidget()
        self.EncryptFileTab.setObjectName(u"EncryptFileTab")
        self.FileTabWidget.addTab(self.EncryptFileTab, "")
        self.DecryptFileTab = QWidget()
        self.DecryptFileTab.setObjectName(u"DecryptFileTab")
        self.FileTabWidget.addTab(self.DecryptFileTab, "")
        self.stackedWidget.addWidget(self.FileStackedWidget)
        self.ContainerStackedWidget = QWidget()
        self.ContainerStackedWidget.setObjectName(u"ContainerStackedWidget")
        self.ContainerTabWidget = QTabWidget(self.ContainerStackedWidget)
        self.ContainerTabWidget.setObjectName(u"ContainerTabWidget")
        self.ContainerTabWidget.setGeometry(QRect(0, 0, 511, 441))
        self.CreateContainerTab = QWidget()
        self.CreateContainerTab.setObjectName(u"CreateContainerTab")
        self.ContainerTabWidget.addTab(self.CreateContainerTab, "")
        self.OpenContainerTab = QWidget()
        self.OpenContainerTab.setObjectName(u"OpenContainerTab")
        self.ContainerTabWidget.addTab(self.OpenContainerTab, "")
        self.stackedWidget.addWidget(self.ContainerStackedWidget)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 60, 111, 161))
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.pushTextButton = QPushButton(self.widget)
        self.sidePanelButtonGroup = QButtonGroup(MainWindow)
        self.sidePanelButtonGroup.setObjectName(u"sidePanelButtonGroup")
        self.sidePanelButtonGroup.addButton(self.pushTextButton)
        self.pushTextButton.setObjectName(u"pushTextButton")
        self.pushTextButton.setMinimumSize(QSize(0, 40))
        self.pushTextButton.setCheckable(True)
        self.pushTextButton.setChecked(True)

        self.verticalLayout.addWidget(self.pushTextButton)

        self.pushFileButton = QPushButton(self.widget)
        self.sidePanelButtonGroup.addButton(self.pushFileButton)
        self.pushFileButton.setObjectName(u"pushFileButton")
        self.pushFileButton.setMinimumSize(QSize(0, 40))
        self.pushFileButton.setCheckable(True)

        self.verticalLayout.addWidget(self.pushFileButton)

        self.pushContainerButton = QPushButton(self.widget)
        self.sidePanelButtonGroup.addButton(self.pushContainerButton)
        self.pushContainerButton.setObjectName(u"pushContainerButton")
        self.pushContainerButton.setMinimumSize(QSize(0, 40))
        self.pushContainerButton.setCheckable(True)

        self.verticalLayout.addWidget(self.pushContainerButton)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 640, 22))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        self.TextTabWidget.setCurrentIndex(0)
        self.FileTabWidget.setCurrentIndex(0)
        self.ContainerTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)

        # Buttons
        self.pushTextButton.clicked.connect(self.displayTextStackedWidget)
        self.pushFileButton.clicked.connect(self.displayFileStackedWidget)
        self.pushContainerButton.clicked.connect(self.displayContainerStackedWidget)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"AES PyEncryptor", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Logs", None))
        self.EncryptTextButton.setText(QCoreApplication.translate("MainWindow", u"Encrypt", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Input Text", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Output Encrypted Text", None))
        self.TextTabWidget.setTabText(self.TextTabWidget.indexOf(self.EncryptTextTab), QCoreApplication.translate("MainWindow", u"Encryption", None))
        self.DecryptTextButton.setText(QCoreApplication.translate("MainWindow", u"Decrypt", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Input Encrypted Text", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Output Decrypted Text", None))
        self.TextTabWidget.setTabText(self.TextTabWidget.indexOf(self.DecryptTextTab), QCoreApplication.translate("MainWindow", u"Decryption", None))
        self.FileTabWidget.setTabText(self.FileTabWidget.indexOf(self.EncryptFileTab), QCoreApplication.translate("MainWindow", u"Encryption", None))
        self.FileTabWidget.setTabText(self.FileTabWidget.indexOf(self.DecryptFileTab), QCoreApplication.translate("MainWindow", u"Decryption", None))
        self.ContainerTabWidget.setTabText(self.ContainerTabWidget.indexOf(self.CreateContainerTab), QCoreApplication.translate("MainWindow", u"Create", None))
        self.ContainerTabWidget.setTabText(self.ContainerTabWidget.indexOf(self.OpenContainerTab), QCoreApplication.translate("MainWindow", u"Open", None))
        self.pushTextButton.setText(QCoreApplication.translate("MainWindow", u"Text", None))
        self.pushFileButton.setText(QCoreApplication.translate("MainWindow", u"File", None))
        self.pushContainerButton.setText(QCoreApplication.translate("MainWindow", u"Container", None))
    # retranslateUi
    
    def displayTextStackedWidget(self):
        # Find the index of self.TextStackedWidget in self.stackedWidget
        index = self.stackedWidget.indexOf(self.TextStackedWidget)
        self.stackedWidget.setCurrentIndex(index)

    def displayFileStackedWidget(self):
        # Find the index of self.FileStackedWidget in self.stackedWidget
        index = self.stackedWidget.indexOf(self.FileStackedWidget)
        self.stackedWidget.setCurrentIndex(index)

    def displayContainerStackedWidget(self):
        # Find the index of self.ContainerStackedWidget in self.stackedWidget
        index = self.stackedWidget.indexOf(self.ContainerStackedWidget)
        self.stackedWidget.setCurrentIndex(index)